# Generated by Django 4.2.1 on 2023-07-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='titulo',
            new_name='servico',
        ),
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
