# Generated by Django 4.2.1 on 2023-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_rename_titulo_servico_servico_servico_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
