# Generated by Django 4.2.1 on 2023-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20230531_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(default=True, max_length=80),
        ),
    ]
